### ISSUE TITLE
SPM BUG

### ISSUE THREAD

**Issue by JIANHUA-XUE-EXE** [AaHaHaa/MMTools#1]
Hey! Thanks for your generous sharing. I came across a bug when I ran your examples SPM.M.
<img width="282" alt="image" src="https://github.com/AaHaHaa/MMTools/assets/145174460/9a252c5c-07ab-4aaa-81d5-7d90ded53812">
It seems like it doesn't add path correctly, and the script couldn't find the load_default_GMMNLSE_propagate.

**Comment by AaHaHaa** [comment]
Hi, Jianhua,

Thanks for notifying me. I'll update the code. And thanks for willing to
use my code. I'm happy that someone is considering using it.

I'll check all the examples. I made some examples long ago and might have
moved them around a little bit, so I forgot to check them one by one. By
the way, you can modify it easily. It should add "user_helpers" and
"GMMNLSE algorithm" by having
addpath('../../../GMMNLSE algorithm/','../../../user_helpers/');
Feel free to let me know if there are further issues or if you have any
questions.

Best,
Yi-Hao
