### ISSUE TITLE
A Small Annotation Error

### ISSUE THREAD

**Issue by sulfonic-acid** [AaHaHaa/MMTools#3]
Hi, Yihao.
Thanks for your generous sharing, and it is useful.
I found a small annotation error in the path below (row 53).
path: GMMNLSE/Examples/Gain-rate-equation model/GMNA/PM_GMNA_30um.m
`gain_rate_eqn.t_rep = 2e-7; % Assume 2 MHz here; s; the time required to finish a roundtrip (the inverse repetition rate of the pulse)`
It seems like it should be 5 MHz in here comparing with other files.

**Comment by AaHaHaa** [comment]
Thanks. I fixed it.
