### ISSUE TITLE
Question on Pulse Splitting in SPM Simulation

### ISSUE THREAD

**Issue by JAMES-XUE-EXE** [AaHaHaa/MMTools#8]
![untitled](https://github.com/user-attachments/assets/32134d0f-0bad-4baf-ad2f-68df7745b0af)
Dear Yi-Hao Chen,

  Thank you once again for providing such a valuable resource – your code has been incredibly helpful!
  I have a question about the SPM (Self-Phase Modulation) effect observed in the code. After running the simulation, I noticed that the pulse begins to split in the time domain at around 1 meter, and this splitting becomes more pronounced with increasing fiber length. I am using this toolbox to simulate a mode-locked laser, so I am particularly interested in the stability of the simulation results over longer fiber distances.
  From what I understand, pure SPM (without Raman or self-steepening effects) shouldn’t alter the pulse shape in the time domain. However, I wasn’t able to fully resolve this point from the documentation provided, and I would be grateful for any clarification you could offer on this behavior.
  Thanks again for your dedication to open-source projects and for all the help your code has provided!

**Comment by JAMES-XUE-EXE** [comment]
You can also contact me via email at xuejh5@mail2.sysu.edu.cn

**Comment by AaHaHaa** [comment]
I'm guessing your frequency window is too small so that you have aliasing in time domain. SPM broadens the pulse too much. You need to increase the frequency window size which is the inverse of dt.

**Comment by JAMES-XUE-EXE** [comment]
Thank you very much for your answer! You were absolutely right – after decreasing the value of dt, the pulse distortion is almost entirely eliminated.

**Comment by AaHaHaa** [comment]
In case you have aliasing in frequency domain due to a small time window (because you reduce dt), I suggest sometimes it's important to play with both Nt, the number of sampling points, and dt, the temporal sampling spacing.

Glad that my guess is correct and helps you. Feel free to ask if you have more questions.

**Comment by JAMES-XUE-EXE** [comment]
Hello, and thank you for your previous response! After increasing the data points (primarily by raising Nt), I found that higher Nt values actually led to more instability in the simulation results. I tested with Nt values of 2**12, 2**14, 2**16, and 2**18. Is there any way to prevent this instability?
![2-12](https://github.com/user-attachments/assets/a623632b-1465-4f63-9886-100c02063770)
![2-14](https://github.com/user-attachments/assets/4f9def64-618a-4e3c-b2b5-86306415438e)
![2-16](https://github.com/user-attachments/assets/c908ecc2-f9b3-4ed2-bda5-c07336005d15)
![2-18](https://github.com/user-attachments/assets/dadcfbb5-e927-4cb5-8ee6-2aee0031903d)
Additionally, I reviewed the manual you provided and noticed that only the Raman effect is explicitly separated, while other nonlinear effects seem to be included in the simulation. Could higher-order effects like self-steepening be involved?
I also tested other examples, and in the soliton case, the spectrum shows a sharp peak at the center. Increasing the points didn’t seem to improve this. Any guidance would be greatly appreciated! Thank you again for your help.
![soliton](https://github.com/user-attachments/assets/83405f59-408c-49e1-bcf2-937b766376c1)

**Comment by AaHaHaa** [comment]
Could you provide you code? I cannot guess this time due to few clues.

It seems that you have some sort of aliasing or weird blowup issue. How's your dispersion? Is it flat in your frequency window? n2 is a constant, so I'm not worried.

About self-steepening......I specifically wrote about that in Github readme......
Let me explain again: self-steepening comes from frequency-dependence of nonlinearity. In UPPE, if the nonlinear prefactor is omega, not omega0, self-steepening is always included.
I don't know what you mean other higher-order effects. My code should consider everything about X3.

Thanks for joining the laser world, haha.
By the way, if you school has digital signal processing (DSP) class, I highly recommend that you take it. I took it in my second-year PhD because I struggled a lot with DFT and aliasing in my first year and I realized that I needed a complete picture on this.

**Comment by JAMES-XUE-EXE** [comment]
Thank you for your advice and detailed explanation! I really appreciate the time you’ve taken to help clarify these points and for your suggestion about taking a DSP class.

Regarding the high-order effects question, I should clarify that my reference was to Govind Agrawal’s book, specifically equations 2.3.35 and 2.3.37, which are some lower-order approximations. I wasn’t quite sure if your simulation automatically includes all higher-order terms beyond these approximations or if some might need to be accounted for manually.

Also, the example I mentioned is actually from your toolbox: MMTools-main\GMMNLSE\Examples\Some tutorials\2. SPM. Thanks again for the invaluable support you’ve provided—it’s been a huge help as I work through these simulations.

**Comment by AaHaHaa** [comment]
Oh, so you mean the higher-order dispersion. Please check fiber.betas and the document about it. By default, there are five terms I think, beta0 to beta5, where the inverse group velocity is beta2 and dispersion is the beta3 term.
Please check "7. Broadband SPM-based supercontinuum" in Examples/ folder. It contains examples of using Taylor-series-expanded betas and using beta(omega) from Sellmeier equation, the most general approach.

I increased the number of sampling points to 2^13 and 2^16 in that example and didn't see any difference. What did you also change?

**Comment by AaHaHaa** [comment]
Although I don't think this matters to you, please redownload the code. I found a bug about the noise modeling, which implemented recently, last night and updated it.

**Comment by JAMES-XUE-EXE** [comment]
Thanks for the clarification! I initially thought your algorithm was like the usual generalized nonlinear Schrödinger equation, where self-steepening is implemented as a first-order approximation. This approximation typically accounts for the frequency dependence of the nonlinearity to the first order. But if your algorithm operates directly in the frequency domain, it should automatically include the self-steepening effect across all orders.
After you fixed the noise modeling bug, I ran the simulation again, and it’s noticeably improved—even though I didn’t change anything else. Anyway, thanks again for the update.

**Comment by AaHaHaa** [comment]
Glad that you have solved the problem
